---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  # - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[ubuntu]
      - recipe[dev_box::update]
      - recipe[dev_box::default]
      - recipe[dev_box::webkit]
      - recipe[java]
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/java
        - test/integration/webkit
    attributes:
