name 'dev_box'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures dev_box'
long_description 'Installs/Configures dev_box'
version '0.1.0'
chef_version '>= 12.14' if respond_to?(:chef_version)
issues_url 'https://github.com/capnregex/dev_box_cookbook/issues'
source_url 'https://github.com/capnregex/dev_box_cookbook'
depends 'ubuntu', '~> 2.0.1'
